"""SQL static-analysis layer over sqlglot."""

from dblect.sql.parse import SQLParseError, parse_sql
from dblect.sql.patterns import (
    PORTABLE_NON_DETERMINISTIC_BUILTINS,
    AggregateSummary,
    Finding,
    FindingKind,
    GroupBySummary,
    JoinSide,
    JoinSummary,
    WindowSummary,
    all_findings,
    detect_coalesce_on_join_key,
    detect_null_group_after_outer_join,
    detect_unordered_aggregate,
    detect_unordered_window,
    detect_where_on_outer_joined_nullable,
    finding_at,
    list_aggregations,
    list_group_bys,
    list_joins,
    list_windows,
    make_non_determinism_detector,
    scan_all,
)

__all__ = [
    "PORTABLE_NON_DETERMINISTIC_BUILTINS",
    "AggregateSummary",
    "Finding",
    "FindingKind",
    "GroupBySummary",
    "JoinSide",
    "JoinSummary",
    "SQLParseError",
    "WindowSummary",
    "all_findings",
    "detect_coalesce_on_join_key",
    "detect_null_group_after_outer_join",
    "detect_unordered_aggregate",
    "detect_unordered_window",
    "detect_where_on_outer_joined_nullable",
    "finding_at",
    "list_aggregations",
    "list_group_bys",
    "list_joins",
    "list_windows",
    "make_non_determinism_detector",
    "parse_sql",
    "scan_all",
]
