"""SQL static-analysis layer over sqlglot."""

from dblect.sql.parse import (
    JinjaPlaceholder,
    ParsedSQL,
    PlaceholderKind,
    SQLParseError,
)
from dblect.sql.patterns import (
    AggregateSummary,
    Finding,
    FindingKind,
    GroupBySummary,
    JoinSide,
    JoinSummary,
    WindowSummary,
    all_findings,
    detect_coalesce_on_join_key,
    detect_non_deterministic_function,
    detect_null_group_after_outer_join,
    detect_unordered_aggregate,
    detect_unordered_window,
    detect_where_on_outer_joined_nullable,
    list_aggregations,
    list_group_bys,
    list_joins,
    list_windows,
    scan_all,
)

__all__ = [
    "AggregateSummary",
    "Finding",
    "FindingKind",
    "GroupBySummary",
    "JinjaPlaceholder",
    "JoinSide",
    "JoinSummary",
    "ParsedSQL",
    "PlaceholderKind",
    "SQLParseError",
    "WindowSummary",
    "all_findings",
    "detect_coalesce_on_join_key",
    "detect_non_deterministic_function",
    "detect_null_group_after_outer_join",
    "detect_unordered_aggregate",
    "detect_unordered_window",
    "detect_where_on_outer_joined_nullable",
    "list_aggregations",
    "list_group_bys",
    "list_joins",
    "list_windows",
    "scan_all",
]
