"""Map dbt adapter names to sqlglot dialect strings, and gate unvalidated runs.

The dbt manifest exposes ``metadata.adapter_type`` (``"duckdb"``,
``"snowflake"``, ``"bigquery"``, ...). sqlglot speaks "dialects". The two
namespaces overlap a lot but are not the same thing: the mapping here is
the place where dblect commits to a translation.

An adapter is **validated** when dblect's detectors have been exercised
against SQL from that adapter and we trust the results. Only ``duckdb`` is
validated today. Other adapters route through the same sqlglot dialect that
matches by name once the operator opts in via ``--dialect``; until then,
``resolve_dialect`` refuses to silently interpret non-DuckDB SQL as DuckDB.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

ADAPTER_TO_SQLGLOT_DIALECT: Mapping[str, str] = MappingProxyType(
    {
        "duckdb": "duckdb",
    }
)
"""Adapters whose detector behavior dblect has validated end-to-end.

Add an entry here only after running the audit test suite against fixtures
generated by that adapter. The keys are dbt adapter names
(``manifest.metadata.adapter_type``); the values are sqlglot dialect names
(passed through to ``sqlglot.parse_one(..., dialect=...)``).
"""

VALIDATED_DIALECTS: frozenset[str] = frozenset(ADAPTER_TO_SQLGLOT_DIALECT.values())


class UnvalidatedAdapterError(ValueError):
    """The manifest's adapter is not in dblect's validated set.

    Raised when no explicit ``--dialect`` override is in effect and the
    adapter would otherwise be interpreted as something dblect hasn't
    verified detector behavior against. Carries the adapter name so the
    CLI can build an actionable message.
    """

    def __init__(self, adapter_type: str) -> None:
        super().__init__(
            f"adapter `{adapter_type}` is not in dblect's validated set "
            f"({sorted(ADAPTER_TO_SQLGLOT_DIALECT)})"
        )
        self.adapter_type = adapter_type


def resolve_dialect(*, adapter_type: str, explicit_dialect: str | None) -> str:
    """Return the sqlglot dialect to use, or raise `UnvalidatedAdapterError`.

    `explicit_dialect`, if provided, wins unconditionally: passing the flag
    is itself the operator's acknowledgment that they're accepting a
    best-effort interpretation. Without it, the adapter must map to a
    validated dialect.
    """
    if explicit_dialect is not None:
        return explicit_dialect
    mapped = ADAPTER_TO_SQLGLOT_DIALECT.get(adapter_type)
    if mapped is None:
        raise UnvalidatedAdapterError(adapter_type)
    return mapped
