"""Generate the typed ``models`` proxy from a dbt manifest.

``models.stg_orders.order_id`` works at runtime through the lazy proxy with no
codegen, at the cost of editor autocomplete (``__getattr__`` returns a generic
type). The generated stub buys the editor experience back: a class per data-flow
node with a ``ColumnProxy`` attribute per documented column, and a ``models`` value
typed as the namespace of those classes. The runtime object stays the same lazy
proxy, cast to the generated namespace type, so the file is types-only sugar over
the real thing.

This is the Prisma / dlt generated-client pattern: the file lives in its own
package, is gitignored, and is never hand-edited. ``dblect init`` writes it and any
command regenerates it when the manifest is newer. See
``docs/design/dblect_technical_intro.md`` (the ``models`` proxy and generated stubs).
"""

from __future__ import annotations

from dblect.manifest import Manifest, Node, ResourceType

_HEADER = """\
# This file is auto-generated by dblect. Do not edit.
# Regenerate by running `dblect init` (any command refreshes it when the manifest
# is newer). It is types-only: the runtime `models` is the lazy proxy from dblect.
from __future__ import annotations

from typing import cast

from dblect.contracts import ColumnProxy, ModelProxy
from dblect.contracts import models as _models
"""


def model_class_name(node_name: str) -> str:
    """The stub class for a node: PascalCase, underscore-prefixed so it cannot
    collide with a user type (``stg_orders`` -> ``_StgOrders``)."""
    pascal = "".join(part.capitalize() for part in node_name.split("_") if part)
    return f"_{pascal}"


def generate_stub_module(manifest: Manifest) -> str:
    """The source of the ``models`` stub module for ``manifest``.

    One class per data-flow node (model, source, seed, snapshot), keyed by the
    node's name; on a name collision a model wins, since that is what a contract
    body most often references. Names that are not valid Python identifiers are
    skipped rather than emitted as broken code.
    """
    nodes = _nodes_by_name(manifest)
    classes = [_class_block(name, node) for name, node in nodes]
    namespace = _namespace_block(nodes)
    return "\n\n".join((_HEADER, *classes, namespace)) + "\n"


def _nodes_by_name(manifest: Manifest) -> list[tuple[str, Node]]:
    """Each data-flow node by name, models preferred on collision, sorted for a
    stable file (so a no-op regeneration is a no-op diff)."""
    chosen: dict[str, Node] = {}
    for node in manifest.nodes.values():
        if not node.is_data_flow or not node.name.isidentifier():
            continue
        existing = chosen.get(node.name)
        if existing is None or _prefer(node, existing):
            chosen[node.name] = node
    return sorted(chosen.items())


def _prefer(candidate: Node, existing: Node) -> bool:
    """Whether ``candidate`` should replace ``existing`` for a shared name: a model
    displaces a non-model, otherwise the incumbent stays."""
    return (
        candidate.resource_type is ResourceType.MODEL
        and existing.resource_type is not ResourceType.MODEL
    )


def _class_block(name: str, node: Node) -> str:
    cls = model_class_name(name)
    columns = [c for c in node.columns if c.isidentifier()]
    if not columns:
        return f"class {cls}(ModelProxy):\n    pass"
    body = "\n".join(f"    {col}: ColumnProxy" for col in columns)
    return f"class {cls}(ModelProxy):\n{body}"


def _namespace_block(nodes: list[tuple[str, Node]]) -> str:
    if not nodes:
        body = "    pass"
    else:
        body = "\n".join(f"    {name}: {model_class_name(name)}" for name, _ in nodes)
    return f"class _Models:\n{body}\n\n\nmodels = cast('_Models', _models)"
